### ISSUE TITLE
Add support for `res.cookie`

### ISSUE THREAD

**Issue by geritol** [netlify/netlify-plugin-gatsby#101]
res.cookie works in gatsby (eg. `res.cookie("test", true, { httpOnly: false })` but does not work on netlify

**Steps to reproduce**

create a function that set a cookie eg.

```javascript
export default function handler(req, res) {
  res.cookie("test", true, { httpOnly: false })
  res.redirect("/")
}
```

**Expected behavior**

runs and sets cookie locally.
on netlify the function is erroring with 
```
Error when executing function "my-function.js": "res.cookie is not a function"
```

**Can you submit a pull request?**

Yes

**Comment by ascorbic** [comment]
Looking at [the Gatsby docs](https://www.gatsbyjs.com/docs/reference/functions/middleware-and-helpers/#res-helpers), there is no mention of support for `res.cookie()`. It seems that because the dev server uses Express, those are supported by accident, but as this is not documented and may not work in production. For that reason I don't think we should add support.
