### ISSUE TITLE
Could not find a binding for Linux 64-bit with Node.js 12.x

### ISSUE THREAD

**Issue by emarchak** [netlify/netlify-plugin-gatsby#146]
**Describe the bug**

I'm receiving the following error in my builds after installing `gatsby-plugin-netlify` instead of the old gatsby cache plugin. I've tried `Clear cache and deploy site` and rebuilding my lock file. 

Previouly, node 15 has worked well but something is happening with my `node-sass` package combined with this plugin. I also have my `gastby-config` in a ts file that has been transpiling to JS during the build, which might also be connected here. 

Is there anything I could do to inspect this error? I'm not sure how to debug this since it's in the `onPreBuild` phase.

````
Plugin "@netlify/plugin-gatsby" failed

Error: Could not load gatsby-config.js
Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:

Linux 64-bit with Node.js 15.x

This usually happens because your environment has changed since running npm install.
Run npm rebuild node-sass to download the binding for your current environment.
````

(Previously reported in https://github.com/netlify/gatsby-plugin-netlify/issues/28.)

**Steps to reproduce**

My project is open-source, so you can see a failed build with the following:

- Repo: https://github.com/emarchak/randonneurs-to
- PR with failed build: https://github.com/emarchak/randonneurs-to/pull/204
- Failed build: https://app.netlify.com/sites/randonneursto/deploys/616cc583cb0711c3b30ed394

**Expected behavior**

Builds are successful. 🤣 

**Configuration**

It was installed via the UI. My netlify build script is set to `npm run build:production`, which [maps to `gatsby build`](https://github.com/emarchak/randonneurs-to/blob/main/package.json#L66)

**Environment**

I'm not sure how to run the `npx` command since this is on the onPreBuild phase. If there's a good way, please let me know. I have my full build log here, I hope that it helps!

<details>
<summary>Full log from a failed build</summary>

````
6:36:50 PM: Build ready to start
6:36:53 PM: build-image version: dd2f6d8803393d46ac35a4f752a5a46f254c0300
6:36:53 PM: build-image tag: v3.9.1
6:36:53 PM: buildbot version: 349bc0ff8daba7d6ea8d12b21f2f782cbf97d24f
6:36:53 PM: Fetching cached dependencies
6:36:53 PM: Starting to download cache of 965.5MB
6:37:01 PM: Finished downloading cache in 8.007225114s
6:37:01 PM: Starting to extract cache
6:37:41 PM: Finished extracting cache in 40.008764065s
6:37:41 PM: Finished fetching cache in 48.276314496s
6:37:41 PM: Starting to prepare the repo for build
6:37:41 PM: Preparing Git Reference pull/204/head
6:37:43 PM: Parsing package.json dependencies
6:37:44 PM: Starting build script
6:37:44 PM: Installing dependencies
6:37:44 PM: Python version set to 2.7
6:37:45 PM: Started restoring cached node version
6:37:48 PM: Finished restoring cached node version
6:37:48 PM: Attempting node version '15.14.0' from .nvmrc
6:37:49 PM: v15.14.0 is already installed.
6:37:50 PM: Now using node v15.14.0 (npm v7.7.6)
6:37:50 PM: Started restoring cached build plugins
6:37:50 PM: Finished restoring cached build plugins
6:37:50 PM: Attempting ruby version 2.6.2, read from environment
6:37:52 PM: Using ruby version 2.6.2
6:37:52 PM: Using PHP version 5.6
6:37:52 PM: Started restoring cached yarn cache
6:38:07 PM: Finished restoring cached yarn cache
6:38:07 PM: No yarn workspaces detected
6:38:07 PM: Started restoring cached node modules
6:38:07 PM: Finished restoring cached node modules
6:38:08 PM: Installing NPM modules using Yarn version 1.17.0
6:38:08 PM: yarn install v1.17.0
6:38:09 PM: [1/4] Resolving packages...
6:38:10 PM: [2/4] Fetching packages...
6:38:42 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
6:38:42 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-darwin-arm64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-darwin-arm64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-darwin-arm64@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info @netlify/local-functions-proxy-darwin-x64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-darwin-x64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-freebsd-arm64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-freebsd-arm64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-freebsd-arm64@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info @netlify/local-functions-proxy-freebsd-x64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-freebsd-x64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-linux-arm@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-linux-arm@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-linux-arm64@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-linux-arm64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-linux-ia32@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-linux-ia32@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-linux-ppc64@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-linux-ppc64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-openbsd-x64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-openbsd-x64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-win32-ia32@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-win32-ia32@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/local-functions-proxy-win32-ia32@1.1.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info @netlify/local-functions-proxy-win32-x64@1.1.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/local-functions-proxy-win32-x64@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/routing-local-proxy-darwin-arm64@0.34.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/routing-local-proxy-darwin-arm64@0.34.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/routing-local-proxy-darwin-arm64@0.34.1: The CPU architecture "x64" is incompatible with this module.
6:38:42 PM: info @netlify/routing-local-proxy-darwin-x64@0.34.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/routing-local-proxy-darwin-x64@0.34.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: info @netlify/routing-local-proxy-win32-x64@0.34.1: The platform "linux" is incompatible with this module.
6:38:42 PM: info "@netlify/routing-local-proxy-win32-x64@0.34.1" is an optional dependency and failed compatibility check. Excluding it from installation.
6:38:42 PM: [3/4] Linking dependencies...
6:38:42 PM: warning "@apollo/react-hooks > @apollo/client@3.4.16" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
6:38:42 PM: warning "@apollo/react-hooks > @apollo/client > @graphql-typed-document-node/core@3.1.0" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > graphql-tag@2.12.5" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning " > @bugsnag/plugin-react@7.13.2" has unmet peer dependency "@bugsnag/core@^7.0.0".
6:38:42 PM: warning " > @jagi/jest-transform-graphql@1.0.2" has unmet peer dependency "graphql-tag@^2.10.0".
6:38:42 PM: warning " > apollo-boost@0.4.9" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-cache@1.3.5" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-cache-inmemory@1.6.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-client@2.6.10" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-link@1.2.14" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-link-http@1.5.17" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-cache > apollo-utilities@1.3.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning "apollo-boost > apollo-link-error > apollo-link-http-common@0.2.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:38:42 PM: warning " > babel-preset-gatsby@1.14.0" has unmet peer dependency "@babel/core@^7.11.6".
6:38:42 PM: warning " > babel-preset-gatsby@1.14.0" has unmet peer dependency "core-js@^3.0.0".
6:38:42 PM: warning "gatsby > eslint-config-react-app@6.0.0" has unmet peer dependency "babel-eslint@^10.0.0".
6:38:42 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/utils@7.10.0" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
6:38:42 PM: warning "gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/links > @graphql-tools/delegate@7.1.5" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/wrap@7.0.8" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
6:38:42 PM: warning " > gatsby-plugin-image@1.14.1" has unmet peer dependency "@babel/core@^7.12.3".
6:38:42 PM: warning " > gatsby-plugin-sass@4.14.0" has unmet peer dependency "sass@^1.30.0".
6:38:42 PM: warning "gatsby-plugin-sass > sass-loader@10.2.0" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/links@7.1.0" has unmet peer dependency "@apollo/client@~3.2.5 || ~3.3.0".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/links@7.1.0" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
6:38:42 PM: warning "gatsby-source-graphql > @graphql-tools/links > apollo-upload-client@14.1.3" has unmet peer dependency "graphql@14 - 15".
6:38:42 PM: warning " > babel-jest@27.3.0" has unmet peer dependency "@babel/core@^7.8.0".
6:38:42 PM: warning "babel-jest > babel-preset-jest@27.2.0" has unmet peer dependency "@babel/core@^7.0.0".
6:38:42 PM: warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
6:38:42 PM: warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
6:38:42 PM: warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
6:38:42 PM: warning " > eslint-import-resolver-alias@1.1.2" has unmet peer dependency "eslint-plugin-import@>=1.4.0".
6:39:04 PM: [4/4] Building fresh packages...
6:39:18 PM: Done in 69.33s.
6:39:18 PM: NPM modules installed using Yarn
6:39:18 PM: Started restoring cached go cache
6:39:20 PM: Finished restoring cached go cache
6:39:20 PM: Installing Go version 1.12
6:39:20 PM: unset GOOS;
6:39:20 PM: unset GOARCH;
6:39:20 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64';
6:39:20 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.12.linux.amd64/bin:${PATH}";
6:39:20 PM: go version >&2;
6:39:20 PM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.12.linux.amd64.env';
6:39:20 PM: go version go1.12 linux/amd64
6:39:20 PM: Installing missing commands
6:39:20 PM: Verify run directory
6:39:22 PM: ​
6:39:22 PM: ────────────────────────────────────────────────────────────────
6:39:22 PM:   Netlify Build                                                 
6:39:22 PM: ────────────────────────────────────────────────────────────────
6:39:22 PM: ​
6:39:22 PM: ❯ Version
6:39:22 PM:   @netlify/build 18.17.2
6:39:22 PM: ​
6:39:22 PM: ❯ Flags
6:39:22 PM:   baseRelDir: true
6:39:22 PM:   buildId: 616ca582432ee70007ec7531
6:39:22 PM:   deployId: 616ca582432ee70007ec7533
6:39:22 PM: ​
6:39:22 PM: ❯ Current directory
6:39:22 PM:   /opt/build/repo
6:39:22 PM: ​
6:39:22 PM: ❯ Config file
6:39:22 PM:   /opt/build/repo/netlify.toml
6:39:22 PM: ​
6:39:22 PM: ❯ Context
6:39:22 PM:   deploy-preview
6:39:23 PM: ​
6:39:23 PM: ❯ Installing plugins
6:39:23 PM:    - @netlify/plugin-gatsby@1.0.3
6:39:32 PM: ​
6:39:32 PM: ❯ Loading plugins
6:39:32 PM:    - @netlify/plugin-gatsby@1.0.3 from Netlify app
6:39:33 PM: ​
6:39:33 PM: ────────────────────────────────────────────────────────────────
6:39:33 PM:   1. @netlify/plugin-gatsby (onPreBuild event)                  
6:39:33 PM: ────────────────────────────────────────────────────────────────
6:39:33 PM: ​
6:39:35 PM: Found a Gatsby cache. We’re about to go FAST. ⚡️
6:39:41 PM: ​
6:39:41 PM: ────────────────────────────────────────────────────────────────
6:39:41 PM:   Plugin "@netlify/plugin-gatsby" failed                        
6:39:41 PM: ────────────────────────────────────────────────────────────────
6:39:41 PM: ​
6:39:41 PM:   Error message
6:39:41 PM:   Error: Could not load gatsby-config.js
6:39:41 PM:   Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
6:39:41 PM:   Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
6:39:41 PM: ​
6:39:41 PM:   Found bindings for the following environments:
6:39:41 PM:     - Linux 64-bit with Node.js 15.x
6:39:41 PM: ​
6:39:41 PM:   This usually happens because your environment has changed since running `npm install`.
6:39:41 PM:   Run `npm rebuild node-sass` to download the binding for your current environment.
6:39:41 PM: ​
6:39:41 PM:   Plugin details
6:39:41 PM:   Package:        @netlify/plugin-gatsby
6:39:41 PM:   Version:        1.0.3
6:39:41 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-gatsby.git
6:39:41 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-gatsby
6:39:41 PM:   Report issues:  https://github.com/netlify/netlify-plugin-gatsby/issues
6:39:41 PM: ​
6:39:41 PM:   Error location
6:39:41 PM:   In "onPreBuild" event in "@netlify/plugin-gatsby" from Netlify app
6:39:41 PM:       at module.exports (/node_modules/node-sass/lib/binding.js:15:13)
6:39:41 PM: ​
6:39:41 PM:   Resolved config
6:39:41 PM:   build:
6:39:41 PM:     command: npm run build:production
6:39:41 PM:     commandOrigin: ui
6:39:41 PM:     environment:
6:39:41 PM:       - BUTTONDOWN_API_KEY
6:39:41 PM:       - CCN_ENDPOINT
6:39:41 PM:       - GATSBY_BUGSNAG_API_KEY
6:39:41 PM:       - GATSBY_SHOPIFY_TOKEN
6:39:41 PM:       - GRAPHQL_SECRET
6:39:41 PM:       - GRAPHQL_SECRETKEY
6:39:41 PM:       - GRAPHQL_URL
6:39:41 PM:       - GS_COVID_ID
6:39:41 PM:       - GS_PRIVATE_EMAIL
6:39:41 PM:       - GS_PRIVATE_KEY
6:39:41 PM:       - GS_PRIVATE_KEY_ID
6:39:41 PM:       - GS_REGISTRATIONPERM_ID
6:39:41 PM:       - GS_REGISTRATION_ID
6:39:41 PM:       - GTAG_ID
6:39:41 PM:       - HASURA_GRAPHQL_ADMIN_SECRET
6:39:41 PM:       - PERCY_TOKEN
6:39:41 PM:       - REVIEW_ID
6:39:41 PM:       - RO_ENDPOINT
6:39:41 PM:       - RWGPS_API_KEY
6:39:41 PM:       - SENDGRID_API_KEY
6:39:41 PM:       - SLACK_REGISTRATION_WEBHOOK
6:39:41 PM:     publish: /opt/build/repo/public
6:39:41 PM:     publishOrigin: ui
6:39:41 PM:   functionsDirectory: /opt/build/repo/functions
6:39:41 PM:   plugins:
6:39:41 PM:     - inputs: {}
6:39:41 PM:       origin: ui
6:39:41 PM:       package: '@netlify/plugin-gatsby'
6:39:41 PM:   redirects:
6:39:41 PM:     - from: /covid
6:39:41 PM:       status: 301
6:39:41 PM:       to: /registration/covid
6:39:41 PM:     - from: /register
6:39:41 PM:       status: 301
6:39:41 PM:       to: /registration
6:39:41 PM:   redirectsOrigin: config
6:39:41 PM: Caching artifacts
6:39:41 PM: Started saving node modules
6:39:41 PM: Finished saving node modules
6:39:41 PM: Started saving build plugins
6:39:41 PM: Finished saving build plugins
6:39:41 PM: Started saving yarn cache
6:40:03 PM: Finished saving yarn cache
6:40:03 PM: Started saving pip cache
6:40:03 PM: Finished saving pip cache
6:40:03 PM: Started saving emacs cask dependencies
6:40:03 PM: Finished saving emacs cask dependencies
6:40:03 PM: Started saving maven dependencies
6:40:03 PM: Finished saving maven dependencies
6:40:03 PM: Started saving boot dependencies
6:40:03 PM: Finished saving boot dependencies
6:40:03 PM: Started saving rust rustup cache
6:40:03 PM: Finished saving rust rustup cache
6:40:03 PM: Started saving go dependencies
6:40:05 PM: Finished saving go dependencies
6:40:05 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:40:05 PM: Creating deploy upload records
6:40:05 PM: Failing build: Failed to build site
6:40:05 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
6:40:05 PM: Finished processing build request in 3m12.559617364s
````

</details>

**Can you submit a pull request?**

Yes! I'll need help knowing what to change, but happy to lend a hand.

Thanks for the hard work!

**Comment by ChuaTheDog** [comment]
I have the same issue. The Option "Clear cache and deploy" does not help. Updating to gatsby 4 is causing issues due to other dependencies not your updated.

**Comment by ascorbic** [comment]
Can you set the env var `AWS_LAMBDA_JS_RUNTIME` in the UI to `nodejs14.x`, and `NODE_VERSION` to 14

**Comment by ChuaTheDog** [comment]
Did not work. Still got the issue with node-sass

**Comment by ascorbic** [comment]
Can you share the full logs

**Comment by ChuaTheDog** [comment]
`10:32:18 AM: Build ready to start
10:32:19 AM: build-image version: c5b01a919d3e16af69445c5de0cacb49efbb1a23 (focal)
10:32:19 AM: build-image tag: v4.4.0
10:32:19 AM: buildbot version: f02fd0bfaf4d9deaa39681e4440772fbbd5ef7a5
10:32:19 AM: Building without cache
10:32:19 AM: Starting to prepare the repo for build
10:32:20 AM: No cached dependencies found. Cloning fresh repo
10:32:20 AM: git clone https://github.com/ChuaTheDog/denniseitner
10:32:22 AM: Preparing Git Reference refs/heads/development
10:32:23 AM: Parsing package.json dependencies
10:32:23 AM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions' versus 'functions/' in the Netlify UI
10:32:24 AM: Starting build script
10:32:24 AM: Installing dependencies
10:32:24 AM: Python version set to 2.7
10:32:24 AM: Downloading and installing node v14.18.1...
10:32:25 AM: Downloading https://nodejs.org/dist/v14.18.1/node-v14.18.1-linux-x64.tar.xz...
10:32:25 AM: Computing checksum with sha256sum
10:32:25 AM: Checksums matched!
10:32:28 AM: Now using node v14.18.1 (npm v6.14.15)
10:32:28 AM: Started restoring cached build plugins
10:32:28 AM: Finished restoring cached build plugins
10:32:28 AM: Attempting ruby version 2.7.2, read from environment
10:32:29 AM: Using ruby version 2.7.2
10:32:30 AM: Using PHP version 8.0
10:32:30 AM: Started restoring cached node modules
10:32:30 AM: Finished restoring cached node modules
10:32:30 AM: Installing NPM modules using NPM version 6.14.15
10:33:48 AM: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
10:33:48 AM: > sharp@0.29.1 install /opt/build/repo/node_modules/sharp
10:33:48 AM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
10:33:50 AM: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
10:33:51 AM: > puppeteer@3.3.0 install /opt/build/repo/node_modules/puppeteer
10:33:51 AM: > node install.js
10:33:59 AM: Chromium (756035) downloaded to /opt/build/repo/node_modules/puppeteer/.local-chromium/linux-756035
10:33:59 AM: > node-sass@6.0.1 install /opt/build/repo/node_modules/node-sass
10:33:59 AM: > node scripts/install.js
10:34:00 AM: Downloading binary from https://github.com/sass/node-sass/releases/download/v6.0.1/linux-x64-83_binding.node
10:34:00 AM: Download complete
10:34:00 AM: Binary saved to /opt/build/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
10:34:00 AM: Caching binary to /opt/buildhome/.npm/node-sass/6.0.1/linux-x64-83_binding.node
10:34:00 AM: > core-js@2.6.12 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
10:34:00 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:34:00 AM: > core-js@3.17.3 postinstall /opt/build/repo/node_modules/core-js
10:34:00 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:34:01 AM: > core-js-pure@3.17.3 postinstall /opt/build/repo/node_modules/core-js-pure
10:34:01 AM: > node -e "try{require('./postinstall')}catch(e){}"
10:34:02 AM: > gatsby-telemetry@2.13.0 postinstall /opt/build/repo/node_modules/gatsby-telemetry
10:34:02 AM: > node src/postinstall.js || true
10:34:02 AM: > gatsby-cli@3.13.0 postinstall /opt/build/repo/node_modules/gatsby-cli
10:34:02 AM: > node scripts/postinstall.js
10:34:02 AM: > gatsby@3.13.0 postinstall /opt/build/repo/node_modules/gatsby
10:34:02 AM: > node scripts/postinstall.js
10:34:02 AM: > node-sass@6.0.1 postinstall /opt/build/repo/node_modules/node-sass
10:34:02 AM: > node scripts/build.js
10:34:03 AM: Binary found at /opt/build/repo/node_modules/node-sass/vendor/linux-x64-83/binding.node
10:34:03 AM: Testing binary
10:34:03 AM: Binary is fine
10:34:05 AM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
10:34:05 AM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
10:34:05 AM: added 2390 packages from 1202 contributors and audited 2394 packages in 94.554s
10:34:08 AM: 273 packages are looking for funding
10:34:08 AM:   run `npm fund` for details
10:34:08 AM: found 40 vulnerabilities (1 low, 22 moderate, 16 high, 1 critical)
10:34:08 AM:   run `npm audit fix` to fix them, or `npm audit` for details
10:34:08 AM: NPM modules installed
10:34:08 AM: Started restoring cached go cache
10:34:08 AM: Finished restoring cached go cache
10:34:08 AM: go version go1.16.5 linux/amd64
10:34:08 AM: go version go1.16.5 linux/amd64
10:34:08 AM: Installing missing commands
10:34:08 AM: Verify run directory
10:34:10 AM: ​
10:34:10 AM: ────────────────────────────────────────────────────────────────
10:34:10 AM:   Netlify Build                                                 
10:34:10 AM: ────────────────────────────────────────────────────────────────
10:34:10 AM: ​
10:34:10 AM: ❯ Version
10:34:10 AM:   @netlify/build 18.21.3
10:34:10 AM: ​
10:34:10 AM: ❯ Flags
10:34:10 AM:   baseRelDir: true
10:34:10 AM:   buildId: 6184fa21cb6a00e625091e4e
10:34:10 AM:   deployId: 6184fa21cb6a00e625091e50
10:34:10 AM: ​
10:34:10 AM: ❯ Current directory
10:34:10 AM:   /opt/build/repo
10:34:10 AM: ​
10:34:10 AM: ❯ Config file
10:34:10 AM:   /opt/build/repo/netlify.toml
10:34:10 AM: ​
10:34:10 AM: ❯ Context
10:34:10 AM:   production
10:34:10 AM: ​
10:34:10 AM: ❯ Installing plugins
10:34:10 AM:    - @netlify/plugin-gatsby@1.0.3
10:34:20 AM: ​
10:34:20 AM: ❯ Loading plugins
10:34:20 AM:    - @netlify/plugin-gatsby@1.0.3 from Netlify app
10:34:20 AM: ​
10:34:20 AM: ────────────────────────────────────────────────────────────────
10:34:20 AM:   1. @netlify/plugin-gatsby (onPreBuild event)                  
10:34:20 AM: ────────────────────────────────────────────────────────────────
10:34:20 AM: ​
10:34:21 AM: No Gatsby cache found. Building fresh.
10:34:21 AM: ​
10:34:21 AM: ────────────────────────────────────────────────────────────────
10:34:21 AM:   Plugin "@netlify/plugin-gatsby" failed                        
10:34:21 AM: ────────────────────────────────────────────────────────────────
10:34:21 AM: ​
10:34:21 AM:   Error message
10:34:21 AM:   Error: Could not load gatsby-config.js
10:34:21 AM:   Missing binding /opt/build/repo/node_modules/node-sass/vendor/linux-x64-72/binding.node
10:34:21 AM:   Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
10:34:21 AM: ​
10:34:21 AM:   Found bindings for the following environments:
10:34:21 AM:     - Linux 64-bit with Node.js 14.x
10:34:21 AM: ​
10:34:21 AM:   This usually happens because your environment has changed since running `npm install`.
10:34:21 AM:   Run `npm rebuild node-sass` to download the binding for your current environment.
10:34:21 AM: ​
10:34:21 AM:   Plugin details
10:34:21 AM:   Package:        @netlify/plugin-gatsby
10:34:21 AM:   Version:        1.0.3
10:34:21 AM:   Repository:     git+https://github.com/netlify/netlify-plugin-gatsby.git
10:34:21 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-gatsby
10:34:21 AM:   Report issues:  https://github.com/netlify/netlify-plugin-gatsby/issues
10:34:21 AM: ​
10:34:21 AM:   Error location
10:34:21 AM:   In "onPreBuild" event in "@netlify/plugin-gatsby" from Netlify app
10:34:21 AM:       at module.exports (/node_modules/node-sass/lib/binding.js:15:13)
10:34:21 AM: ​
10:34:21 AM:   Resolved config
10:34:21 AM:   build:
10:34:21 AM:     command: npm run build
10:34:21 AM:     commandOrigin: ui
10:34:21 AM:     environment:
10:34:21 AM:       - AWS_LAMBDA_JS_RUNTIME
10:34:21 AM:       - NODE_VERSION
10:34:21 AM:     publish: /opt/build/repo/public
10:34:21 AM:     publishOrigin: ui
10:34:21 AM:   functionsDirectory: /opt/build/repo/functions
10:34:21 AM:   plugins:
10:34:21 AM:     - inputs: {}
10:34:21 AM:       origin: ui
10:34:21 AM:       package: '@netlify/plugin-gatsby'
10:34:21 AM: Caching artifacts
10:34:21 AM: Started saving node modules
10:34:21 AM: Finished saving node modules
10:34:21 AM: Started saving build plugins
10:34:21 AM: Finished saving build plugins
10:34:21 AM: Started saving pip cache
10:34:21 AM: Finished saving pip cache
10:34:21 AM: Started saving emacs cask dependencies
10:34:21 AM: Finished saving emacs cask dependencies
10:34:21 AM: Started saving maven dependencies
10:34:21 AM: Finished saving maven dependencies
10:34:21 AM: Started saving boot dependencies
10:34:21 AM: Finished saving boot dependencies
10:34:21 AM: Started saving rust rustup cache
10:34:21 AM: Finished saving rust rustup cache
10:34:21 AM: Started saving go dependencies
10:34:21 AM: Finished saving go dependencies
10:34:24 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:34:24 AM: Creating deploy upload records
10:34:24 AM: Failing build: Failed to build site
10:34:24 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
10:34:24 AM: Finished processing build request in 2m5.101685851s`

**Comment by ascorbic** [comment]
Ah ok. You're using version 1 of the plugin. If you're using Gatsby 4, you should upgrade to the version 2 beta. See the readme for details of how to do it

**Comment by ChuaTheDog** [comment]
V 1.0.3 is the latest version. Beta ist not available on npm. I am not using gatsby version 4 as there are other dependencies that are not compatible. Any other suggestion on how to resolve this?

**Comment by nadiavanleur** [comment]
Simply running `npm i --save @netlify/plugin-gatsby` locally and pushing the updated package and package-lock ended up fixing this issue for me.

I don't understand why though. I had two duplicate repos on Netlify. One of them worked and the other one had the same error as mentioned here.

**Comment by ascorbic** [comment]
I'm closing this. If anybody is experiencing the same issue with version 2 of the build plugin, please open a new issue.
